### PR TITLE
moved VT here, reset counter when back, send OK slack message when ok'ed

### PR DESCRIPTION
**Pull request by RELNO**

### CODE REVIEW

**Comment by yasushisakai** [comment]
(assuming out of the box `miniconda` is all we need but) can we have minimal documentation how to run it in a different env??

**Comment by RELNO** [comment]
Yes, but this should correspond to what fake-table is or supposed to be. At this point there are several instances of fake/virtual tables, the idea here is to consolidate

**Comment by RELNO** [comment]
https://github.com/CityScope/CS_CityIO_Backend/pull/76/commits/468307f025e3398ac4b85a85f363a64d59990100

**Comment by yasushisakai** [comment]
I get the point, plus I don’t know if I want multiple slack bots chasing me. if it’s documented to friendly....

**Comment by RELNO** [comment]
> plus I don’t know if I want multiple slack bots chasing me

Yap, the point is to stop the VM and run just one, local instance of this in the lab. 

What are your plans for these: 
https://github.com/CityScope/CS_CityIO_Backend/tree/master/examples/fake-table
https://github.com/CityScope/CS_CityIO_Backend/blob/master/examples/citymatrix_volpe.json
https://github.com/CityScope/CS_CityIO_Backend/blob/master/examples/virtual_table.json

**Pull request merged**
